/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Состояние сервера и режимы работы */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход по логину и паролю */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/demo-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Быстрый вход по роли (только демо-режим) */
        post: operations["demo_login_api_auth_demo_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Кто я */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Объекты, доступные пользователю */
        get: operations["list_sites_api_sites_get"];
        put?: never;
        /** Создать объект */
        post: operations["create_site_api_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Зоны объектов */
        get: operations["list_zones_api_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Этапы календарного плана */
        get: operations["list_stages_api_stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Методика «этап → техника» */
        get: operations["list_rules_api_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить правило (администратор) */
        put: operations["update_rule_api_rules__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/equipment-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** План и факт по технике для текущего этапа */
        get: operations["equipment_check_api_sites__site_id__equipment_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Журнал проверок объекта */
        get: operations["list_checks_api_sites__site_id__checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Камеры доступных объектов */
        get: operations["list_cameras_api_cameras_get"];
        put?: never;
        /** Добавить камеру по IP-адресу */
        post: operations["add_camera_api_cameras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить камеру по адресу, не сохраняя её */
        post: operations["probe_camera_api_cameras_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/probe/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Закрыть предпросмотр */
        delete: operations["close_probe_api_cameras_probe__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить камеру (кадры-доказательства сохраняются) */
        delete: operations["delete_camera_api_cameras__camera_id__delete"];
        options?: never;
        head?: never;
        /** Изменить камеру */
        patch: operations["patch_camera_api_cameras__camera_id__patch"];
        trace?: never;
    };
    "/api/cameras/{camera_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить связь с камерой */
        post: operations["test_camera_api_cameras__camera_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Последние снимки каждой камеры
         * @description Возвращает не всю историю, а per_camera свежих снимков на камеру — объём ответа не растёт со временем.
         */
        get: operations["list_snapshots_api_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * «Кадры дня» камер — по одному в день за последние дни
         * @description Первый кадр каждой камеры после полудня (SK_DAILY_FRAME_HOUR): по ним видно, как меняется площадка день ото дня.
         */
        get: operations["daily_snapshots_api_snapshots_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Предупреждения по доступным объектам */
        get: operations["list_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка предупреждения */
        get: operations["get_alert_api_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ответить на предупреждение (сменить статус) */
        post: operations["act_api_alerts__alert_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Готовые примеры снимков */
        get: operations["samples_api_analyze_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Разобрать фото и сверить с этапом объекта или правилом */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Данные страницы сверки без входа */
        get: operations["public_demo_api_public_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Разобрать фото без входа */
        post: operations["public_analyze_api_public_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводка нарушений за 7 дней */
        get: operations["weekly_api_reports_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Принять кадр с детекциями */
        post: operations["ingest_snapshot_api_ingest_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Что видит анализ на каждой камере прямо сейчас */
        get: operations["live_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracker/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Камеры для сервиса разметки
         * @description Какие потоки читать из шлюза. Логин шлюза — sk-tracker, пароль — ключ сервиса. Заголовок X-Api-Key — тот же ключ.
         */
        get: operations["tracker_cameras_api_tracker_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/equipment-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Сколько работала техника по часам (по рамкам сервиса разметки)
         * @description По часу, камере и типу техники: сколько машин сразу, сколько минут в кадре и сколько из них двигалась.
         *     Одну машину могут видеть две камеры — складывать минуты разных камер нельзя, лучше брать максимум по зоне.
         */
        get: operations["equipment_usage_api_sites__site_id__equipment_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracker/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Состояние сервиса разметки: подключён ли, идут ли рамки, последняя ошибка формата */
        get: operations["tracker_status_api_tracker_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Журнал действий, новые сверху */
        get: operations["list_events_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить объект целиком */
        delete: operations["delete_site_api_sites__site_id__delete"];
        options?: never;
        head?: never;
        /** Изменить объект */
        patch: operations["update_site_api_sites__site_id__patch"];
        trace?: never;
    };
    "/api/sites/{site_id}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить зону */
        post: operations["create_zone_api_sites__site_id__zones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones/{zone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить пустую зону */
        delete: operations["delete_zone_api_zones__zone_id__delete"];
        options?: never;
        head?: never;
        /** Изменить зону */
        patch: operations["update_zone_api_zones__zone_id__patch"];
        trace?: never;
    };
    "/api/sites/{site_id}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить этап */
        post: operations["create_stage_api_sites__site_id__stages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stages/{stage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить этап */
        delete: operations["delete_stage_api_stages__stage_id__delete"];
        options?: never;
        head?: never;
        /** Изменить этап */
        patch: operations["update_stage_api_stages__stage_id__patch"];
        trace?: never;
    };
    "/api/stages/{stage_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Отметить, сколько работ сделано по факту */
        patch: operations["set_stage_progress_api_stages__stage_id__progress_patch"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сотрудники */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Завести сотрудника */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить сотрудника */
        delete: operations["delete_user_api_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Изменить сотрудника */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Задать пароль */
        post: operations["set_password_api_users__user_id__password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertActionIn */
        AlertActionIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "acknowledged" | "confirmed" | "prescribed" | "resolved" | "false_positive";
            /**
             * Comment
             * @default
             */
            comment: string;
            /** Duedate */
            dueDate?: string | null;
        };
        /** AlertEventOut */
        AlertEventOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Who */
            who: string;
            /** Text */
            text: string;
        };
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Siteid */
            siteId: string;
            /** Zoneid */
            zoneId: string;
            /** Stageid */
            stageId: string | null;
            /** Cameraid */
            cameraId: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "missing" | "count_below" | "unexpected" | "idle" | "camera_offline";
            /**
             * Severity
             * @enum {string}
             */
            severity: "high" | "medium" | "low";
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "acknowledged" | "confirmed" | "prescribed" | "resolved" | "false_positive";
            /** Isopen */
            isOpen: boolean;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Consequence */
            consequence: string;
            /** Advice */
            advice: string;
            /** Equipment */
            equipment: ("excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane") | null;
            /** Expected */
            expected: number | null;
            /** Observed */
            observed: number | null;
            /** Prescriptionno */
            prescriptionNo: string | null;
            /** Prescriptiondue */
            prescriptionDue: string | null;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Evidence */
            evidence: string[];
            /** Evidencesnapshots */
            evidenceSnapshots: components["schemas"]["SnapshotOut"][];
            /** History */
            history: components["schemas"]["AlertEventOut"][];
        };
        /**
         * AnalyzeOut
         * @description Результат разбора одного снимка: техника + сверка с правилом этапа.
         */
        AnalyzeOut: {
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /** Supported */
            supported: boolean;
            /** Note */
            note: string | null;
            /** Elapsedms */
            elapsedMs: number;
            /** Imageurl */
            imageUrl: string | null;
            /** Detections */
            detections: components["schemas"]["DetectionOut"][];
            /** Rulekey */
            ruleKey: string;
            /** Stagename */
            stageName: string;
            /** Rows */
            rows: components["schemas"]["CheckRow"][];
            /** Deviations */
            deviations: components["schemas"]["DeviationOut"][];
        };
        /** AuditOut */
        AuditOut: {
            /** Id */
            id: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Actorlogin */
            actorLogin: string;
            /** Actorname */
            actorName: string;
            /** Actorrole */
            actorRole: string;
            /** Action */
            action: string;
            /** Entitytype */
            entityType: string;
            /** Entityid */
            entityId: string | null;
            /** Entityname */
            entityName: string;
            /** Summary */
            summary: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Ip */
            ip: string;
        };
        /** Body_analyze_api_analyze_post */
        Body_analyze_api_analyze_post: {
            /** Image */
            image?: string | null;
            /** Sample */
            sample?: string | null;
            /** Siteid */
            siteId?: string | null;
            /** Rulekey */
            ruleKey?: string | null;
        };
        /** Body_ingest_snapshot_api_ingest_snapshots_post */
        Body_ingest_snapshot_api_ingest_snapshots_post: {
            /** Camera Id */
            camera_id: string;
            /**
             * Detections
             * @description JSON: [{"type":"excavator","confidence":0.94,"box":{"x":..,"y":..,"w":..,"h":..}}]
             */
            detections: string;
            /** Image */
            image: string;
            /** Taken At */
            taken_at?: string | null;
            /** Model */
            model?: string | null;
        };
        /** Body_public_analyze_api_public_analyze_post */
        Body_public_analyze_api_public_analyze_post: {
            /** Rulekey */
            ruleKey: string;
            /** Image */
            image?: string | null;
            /** Sample */
            sample?: string | null;
        };
        /** BoxOut */
        BoxOut: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
        };
        /** CameraIn */
        CameraIn: {
            /** Siteid */
            siteId: string;
            /** Name */
            name: string;
            /** Zoneid */
            zoneId?: string | null;
            /** Newzonename */
            newZoneName?: string | null;
            /**
             * Newzonekind
             * @default work
             * @enum {string}
             */
            newZoneKind: "work" | "gate" | "storage";
            connection: components["schemas"]["ConnectionIn"];
            /**
             * Allowoffline
             * @default false
             */
            allowOffline: boolean;
        };
        /** CameraOut */
        CameraOut: {
            /** Id */
            id: string;
            /** Siteid */
            siteId: string;
            /** Zoneid */
            zoneId: string;
            /** Name */
            name: string;
            /** Online */
            online: boolean;
            /** Enabled */
            enabled: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "offline" | "unknown";
            /**
             * Sourcetype
             * @constant
             */
            sourceType: "rtsp";
            /** Address */
            address: string | null;
            /** Hascredentials */
            hasCredentials: boolean;
            /** Demo */
            demo: boolean;
            /** Streampath */
            streamPath: string;
            /** Lasterror */
            lastError: string | null;
            /** Lastsnapshotat */
            lastSnapshotAt: string | null;
            /** Scene */
            scene: string;
        };
        /** CameraPatch */
        CameraPatch: {
            /** Name */
            name?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Zoneid */
            zoneId?: string | null;
            connection?: components["schemas"]["ConnectionIn"] | null;
        };
        /** CheckRow */
        CheckRow: {
            /**
             * Type
             * @enum {string}
             */
            type: "excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane";
            /** Need */
            need: number;
            /** Have */
            have: number;
            /**
             * State
             * @enum {string}
             */
            state: "ok" | "low" | "missing";
            /** Why */
            why: string;
        };
        /** CheckRunOut */
        CheckRunOut: {
            /** Id */
            id: string;
            /** Siteid */
            siteId: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Trigger */
            trigger: string;
            /** Stageid */
            stageId: string | null;
            /** Coverage */
            coverage: boolean;
            /** Observed */
            observed: {
                [key: string]: number;
            };
            /** Arriving */
            arriving: {
                [key: string]: number;
            };
            /** Violations */
            violations: {
                [key: string]: unknown;
            }[];
        };
        /** ConnectionIn */
        ConnectionIn: {
            /**
             * Protocol
             * @default rtsp
             * @constant
             */
            protocol: "rtsp";
            /** Host */
            host: string;
            /** Port */
            port?: number | null;
            /**
             * Path
             * @default /
             */
            path: string;
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
        };
        /** DayCount */
        DayCount: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /**
         * DemoFeedOut
         * @description Демо-ролик как RTSP-адрес — для быстрой настройки в форме «Добавить камеру».
         */
        DemoFeedOut: {
            /** Clip */
            clip: string;
            /** Title */
            title: string;
            /** Host */
            host: string;
            /** Port */
            port: number;
            /** Path */
            path: string;
        };
        /** DemoLoginIn */
        DemoLoginIn: {
            /**
             * Role
             * @enum {string}
             */
            role: "foreman" | "manager" | "inspector" | "admin";
        };
        /** DemoOut */
        DemoOut: {
            /** Rules */
            rules: components["schemas"]["RuleOut"][];
            /** Samples */
            samples: components["schemas"]["SampleOut"][];
            /** Provider */
            provider: string;
        };
        /** DetectionOut */
        DetectionOut: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane";
            /** Confidence */
            confidence: number;
            box: components["schemas"]["BoxOut"];
            /** Moving */
            moving?: boolean | null;
        };
        /** DeviationOut */
        DeviationOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "missing" | "count_below" | "unexpected";
            /**
             * Type
             * @enum {string}
             */
            type: "excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane";
            /** Need */
            need: number | null;
            /** Have */
            have: number;
            /** Title */
            title: string;
            /** Why */
            why: string;
        };
        /**
         * EquipmentCheckOut
         * @description Сравнение «нужно по плану / видим на камерах» для текущего этапа объекта.
         */
        EquipmentCheckOut: {
            /** Siteid */
            siteId: string;
            /** Stageid */
            stageId: string | null;
            /** Stagename */
            stageName: string | null;
            /** Coverage */
            coverage: boolean;
            /** Checkedat */
            checkedAt: string | null;
            /** Rows */
            rows: components["schemas"]["CheckRow"][];
            /** Extra */
            extra: components["schemas"]["ExtraRow"][];
            /** Arriving */
            arriving: {
                [key: string]: number;
            };
        };
        /**
         * EquipmentUsageOut
         * @description Сколько работала техника за час на одной камере (по рамкам сервиса разметки).
         */
        EquipmentUsageOut: {
            /**
             * Hour
             * Format: date-time
             */
            hour: string;
            /** Cameraid */
            cameraId: string;
            /** Zonekind */
            zoneKind: string;
            /**
             * Type
             * @enum {string}
             */
            type: "excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane";
            /** Maxcount */
            maxCount: number;
            /** Presentmin */
            presentMin: number;
            /** Movingmin */
            movingMin: number;
        };
        /** ExtraRow */
        ExtraRow: {
            /**
             * Type
             * @enum {string}
             */
            type: "excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane";
            /** Have */
            have: number;
            /** Why */
            why: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestOut */
        IngestOut: {
            /** Accepted */
            accepted: boolean;
            /** Detections */
            detections: number;
            /** Note */
            note: string;
        };
        /**
         * LiveCameraOut
         * @description Что видит анализ на камере прямо сейчас (обновляется каждые 2 секунды).
         */
        LiveCameraOut: {
            /** Cameraid */
            cameraId: string;
            /** Online */
            online: boolean;
            /** Error */
            error: string | null;
            /** Receivedat */
            receivedAt: string | null;
            /** Analyzedat */
            analyzedAt: string | null;
            /** Analyzed */
            analyzed: boolean | null;
            /** Note */
            note: string | null;
            /** Detections */
            detections: components["schemas"]["DetectionOut"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** LoginIn */
        LoginIn: {
            /** Login */
            login: string;
            /** Password */
            password: string;
        };
        /** MetaOut */
        MetaOut: {
            /** Version */
            version: string;
            /** Demomode */
            demoMode: boolean;
            /** Analysisprovider */
            analysisProvider: string;
            /** Timezone */
            timezone: string;
            /** Servertime */
            serverTime: string;
            /** Database */
            database: string;
            /** Authmode */
            authMode: string;
            /** Keycloak */
            keycloak: {
                [key: string]: unknown;
            } | null;
            video: components["schemas"]["VideoOut"];
            tracker: components["schemas"]["TrackerOut"];
            /** Demofeeds */
            demoFeeds: components["schemas"]["DemoFeedOut"][];
        };
        /** NamedCount */
        NamedCount: {
            /** Key */
            key: string;
            /** Count */
            count: number;
        };
        /** PasswordIn */
        PasswordIn: {
            /** Password */
            password: string;
        };
        /** ProbeOut */
        ProbeOut: {
            /** Ok */
            ok: boolean;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Elapsedms */
            elapsedMs: number;
            /** Previewpath */
            previewPath?: string | null;
        };
        /** RuleIn */
        RuleIn: {
            /** Required */
            required: components["schemas"]["RuleRequirement"][];
            /**
             * Allowed
             * @default []
             */
            allowed: ("excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane")[];
            /**
             * Unexpected
             * @default []
             */
            unexpected: components["schemas"]["RuleUnexpected"][];
            /** Confirmaftersnapshots */
            confirmAfterSnapshots: number;
        };
        /** RuleOut */
        RuleOut: {
            /** Key */
            key: string;
            /** Stagename */
            stageName: string;
            /** Description */
            description: string;
            /** Required */
            required: components["schemas"]["RuleRequirement"][];
            /** Allowed */
            allowed: ("excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane")[];
            /** Unexpected */
            unexpected: components["schemas"]["RuleUnexpected"][];
            /** Confirmaftersnapshots */
            confirmAfterSnapshots: number;
        };
        /** RuleRequirement */
        RuleRequirement: {
            /**
             * Type
             * @enum {string}
             */
            type: "excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane";
            /** Min */
            min: number;
            /**
             * Why
             * @default
             */
            why: string;
            /**
             * Risk
             * @default
             */
            risk: string;
        };
        /** RuleUnexpected */
        RuleUnexpected: {
            /**
             * Type
             * @enum {string}
             */
            type: "excavator" | "dump_truck" | "roller" | "manipulator" | "mixer" | "bulldozer" | "truck" | "crane";
            /**
             * Why
             * @default
             */
            why: string;
            /**
             * Risk
             * @default
             */
            risk: string;
        };
        /** SampleOut */
        SampleOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Imageurl */
            imageUrl: string;
        };
        /** SiteCount */
        SiteCount: {
            /** Siteid */
            siteId: string;
            /** Name */
            name: string;
            /** Count */
            count: number;
            /** High */
            high: number;
        };
        /** SiteIn */
        SiteIn: {
            /** Name */
            name: string;
            /**
             * Address
             * @default
             */
            address: string;
            /**
             * Contractor
             * @default
             */
            contractor: string;
            /**
             * Kind
             * @default other
             * @enum {string}
             */
            kind: "residential" | "public" | "road" | "industrial" | "other";
            /** Foremanid */
            foremanId?: string | null;
        };
        /** SiteOut */
        SiteOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Contractor */
            contractor: string;
            /** Foreman */
            foreman: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "residential" | "public" | "road" | "industrial" | "other";
            /** Currentstageid */
            currentStageId: string | null;
            /** Planprogress */
            planProgress: number | null;
            /** Factprogress */
            factProgress: number | null;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /** Id */
            id: string;
            /** Cameraid */
            cameraId: string;
            /**
             * Takenat
             * Format: date-time
             */
            takenAt: string;
            /** Imageurl */
            imageUrl: string;
            /** Detections */
            detections: components["schemas"]["DetectionOut"][];
            /** Analyzed */
            analyzed: boolean;
            /** Provider */
            provider: string | null;
            /** Note */
            note: string | null;
            /** Daily */
            daily: boolean;
        };
        /** StageIn */
        StageIn: {
            /** Name */
            name: string;
            /**
             * Level
             * @default 2
             * @enum {integer}
             */
            level: 1 | 2;
            /** Parentid */
            parentId?: string | null;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Rulekey */
            ruleKey?: string | null;
            /** Factprogress */
            factProgress?: number | null;
        };
        /** StageOut */
        StageOut: {
            /** Id */
            id: string;
            /** Siteid */
            siteId: string;
            /** Parentid */
            parentId: string | null;
            /** Level */
            level: number;
            /** Name */
            name: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "in_progress" | "planned";
            /** Rulekey */
            ruleKey: string | null;
            /** Planprogress */
            planProgress: number;
            /** Factprogress */
            factProgress: number;
            /** Factupdatedat */
            factUpdatedAt: string | null;
        };
        /** StageProgressIn */
        StageProgressIn: {
            /** Factprogress */
            factProgress: number;
        };
        /** TokenOut */
        TokenOut: {
            /** Token */
            token: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * TrackerCameraOut
         * @description Камера для сервиса разметки: какой поток читать из шлюза.
         */
        TrackerCameraOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Siteid */
            siteId: string;
            /** Zonekind */
            zoneKind: string;
            /** Rtspurl */
            rtspUrl: string;
            /** Democlip */
            demoClip: string | null;
        };
        /**
         * TrackerOut
         * @description Рамки в реальном времени от сервиса разметки (WebSocket /api/tracks).
         */
        TrackerOut: {
            /** Enabled */
            enabled: boolean;
            /** Connected */
            connected: boolean;
            /** Videodelayms */
            videoDelayMs: number;
            /** Lastmessageat */
            lastMessageAt: string | null;
        };
        /**
         * TrackerStatusOut
         * @description Что происходит с сервисом разметки — для отладки интеграции (только администратору и руководителю).
         */
        TrackerStatusOut: {
            /** Enabled */
            enabled: boolean;
            /** Connected */
            connected: boolean;
            /** Messages */
            messages: number;
            /** Lastmessageat */
            lastMessageAt: string | null;
            /** Problem */
            problem: string | null;
            /** Problemat */
            problemAt: string | null;
            /** Viewers */
            viewers: number;
        };
        /** UserIn */
        UserIn: {
            /** Login */
            login: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "foreman" | "manager" | "inspector" | "admin";
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Siteids
             * @default []
             */
            siteIds: string[];
            /** Password */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Login */
            login: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "foreman" | "manager" | "inspector" | "admin";
            /** Phone */
            phone: string;
            /** Siteids */
            siteIds: string[];
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
        };
        /** UserPatch */
        UserPatch: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: ("foreman" | "manager" | "inspector" | "admin") | null;
            /** Phone */
            phone?: string | null;
            /** Siteids */
            siteIds?: string[] | null;
            /** Isactive */
            isActive?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoOut */
        VideoOut: {
            /** Enabled */
            enabled: boolean;
            /** Webrtcurl */
            webrtcUrl: string;
            /** Frameintervals */
            frameIntervalS: number;
            /** Checkintervals */
            checkIntervalS: number;
        };
        /** WeeklyReportOut */
        WeeklyReportOut: {
            /**
             * Datefrom
             * Format: date
             */
            dateFrom: string;
            /**
             * Dateto
             * Format: date
             */
            dateTo: string;
            /** Total */
            total: number;
            /** Open */
            open: number;
            /** Resolved */
            resolved: number;
            /** Falsepositive */
            falsePositive: number;
            /** Byday */
            byDay: components["schemas"]["DayCount"][];
            /** Bysite */
            bySite: components["schemas"]["SiteCount"][];
            /** Bykind */
            byKind: components["schemas"]["NamedCount"][];
            /** Byequipment */
            byEquipment: components["schemas"]["NamedCount"][];
        };
        /** ZoneIn */
        ZoneIn: {
            /** Name */
            name: string;
            /**
             * Kind
             * @default work
             * @enum {string}
             */
            kind: "work" | "gate" | "storage";
        };
        /** ZoneOut */
        ZoneOut: {
            /** Id */
            id: string;
            /** Siteid */
            siteId: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "work" | "gate" | "storage";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_login_api_auth_demo_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_sites_api_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"][];
                };
            };
        };
    };
    create_site_api_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_zones_api_zones_get: {
        parameters: {
            query?: {
                /** @description Ограничить одним объектом */
                siteId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stages_api_stages_get: {
        parameters: {
            query?: {
                /** @description Ограничить одним объектом */
                siteId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    update_rule_api_rules__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    equipment_check_api_sites__site_id__equipment_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_checks_api_sites__site_id__checks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cameras_api_cameras_get: {
        parameters: {
            query?: {
                /** @description Ограничить одним объектом */
                siteId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_camera_api_cameras_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_camera_api_cameras_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_probe_api_cameras_probe__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_camera_api_cameras__camera_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_camera_api_cameras__camera_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_camera_api_cameras__camera_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_snapshots_get: {
        parameters: {
            query?: {
                /** @description Ограничить одним объектом */
                siteId?: string | null;
                cameraId?: string | null;
                perCamera?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_snapshots_api_snapshots_daily_get: {
        parameters: {
            query?: {
                /** @description Ограничить одним объектом */
                siteId?: string | null;
                cameraId?: string | null;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_alerts_get: {
        parameters: {
            query?: {
                /** @description Ограничить одним объектом */
                siteId?: string | null;
                state?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_api_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    act_api_alerts__alert_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertActionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    samples_api_analyze_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"][];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_demo_api_public_demo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoOut"];
                };
            };
        };
    };
    public_analyze_api_public_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_public_analyze_api_public_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekly_api_reports_weekly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReportOut"];
                };
            };
        };
    };
    ingest_snapshot_api_ingest_snapshots_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_snapshot_api_ingest_snapshots_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_live_get: {
        parameters: {
            query?: {
                /** @description Ограничить одним объектом */
                siteId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveCameraOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tracker_cameras_api_tracker_cameras_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackerCameraOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    equipment_usage_api_sites__site_id__equipment_usage_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentUsageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tracker_status_api_tracker_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackerStatusOut"];
                };
            };
        };
    };
    list_events_api_audit_get: {
        parameters: {
            query?: {
                /** @description Логин того, кто действовал */
                actor?: string | null;
                /** @description Вид действия или его начало: camera, camera.delete, login… */
                action?: string | null;
                entityType?: string | null;
                /** @description Поиск по тексту записи */
                q?: string | null;
                since?: string | null;
                /** @description Постранично: записи старше этой */
                beforeId?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_site_api_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_site_api_sites__site_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_zone_api_sites__site_id__zones_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_zone_api_zones__zone_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_zone_api_zones__zone_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stage_api_sites__site_id__stages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stage_api_stages__stage_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stage_api_stages__stage_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_stage_progress_api_stages__stage_id__progress_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageProgressIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_users__user_id__password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
